# Generated by Django 5.2.5 on 2025-10-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_person', models.CharField(max_length=50)),
            ],
        ),
    ]
